export const ROUTE_DEFINITION = {
  APP: {
    HOME: '',
    NOT_FOUND: '**',
    FOUNDATIONS: 'foundations',
    FORMS: 'forms',
  },
  FOUNDATIONS: {
    COLORS: 'colors',
    TYPOGRAPHY: 'typography',
  },
  FORMS: {
    INPUT_CHECKBOX: 'checkbox',
    INPUT_RADIO: 'radio',
    INPUT_RANGE: 'range',
    INPUT_SELECT: 'select',
    INPUT_TEXT: 'text',
    INPUT_TEXTAREA: 'textarea',
    INPUT_TOGGLE: 'toggle',
    INPUT_PASSWORD: 'password',
    INPUT_MULTISELECT: 'multiselect',
    INPUT_AUTOCOMPLETE: 'autocomplete',
  },
} as const;

export const ROUTE_TITLE = {
  APP: {
    HOME: 'Design System',
    NOT_FOUND: 'Not Found',
  },
  FOUNDATIONS: {
    ROOT: 'Foundations',
    OVERVIEW: 'Foundations',
    COLOR: 'Color',
    TYPOGRAPHY: 'Typography',
  },
  COMPONENTS: {
    ROOT: 'Components',
    OVERVIEW: 'Components',
    ACCORDION: 'Accordion',
    ALERT: 'Alert',
    BADGE: 'Badge',
    BUTTON: 'Button',
    CARD: 'Card',
    CAROUSEL: 'Carousel',
    MARKDOWN: 'Markdown',
    MODAL: 'Modal',
    PROGRESS_BAR: 'Progress Bar',
    SKELETON: 'Skeleton',
    TABS: 'Tabs',
    TOAST: 'Toast',
    TOOLBAR: 'Toolbar',
    TOOLTIP: 'Tooltip',
  },
  FORMS: {
    ROOT: 'Forms',
    OVERVIEW: 'Forms',
    CHECKBOX: 'Checkbox',
    RADIO: 'Radio',
    INPUT_RANGE: 'Input Range',
    INPUT_SELECT: 'Input Select',
    INPUT_TEXT: 'Input Text',
    INPUT_TEXTAREA: 'Input Textarea',
    TOGGLE: 'Toggle',
  },
  VISUALS: {
    ROOT: 'Visuals',
    OVERVIEW: 'Visuals',
    BRANDS: 'Brands',
    FLAGS: 'Flags',
    ICONS: 'Icons',
    LIBRARIES: 'Libraries',
    PROJECTS: 'Projects',
  },
} as const;
