export const ROUTE_DEFINITION = {
  APP: {
    HOME: '',
    NOT_FOUND: '**',
    FOUNDATIONS: 'foundations',
    FORMS: 'forms',
    COMPONENTS: 'components',
  },
  FOUNDATIONS: {
    COLORS: 'colors',
    TYPOGRAPHY: 'typography',
  },
  FORMS: {
    INPUT_CHECKBOX: 'checkbox',
    INPUT_RADIO: 'radio',
    INPUT_RANGE: 'range',
    INPUT_SELECT: 'select',
    INPUT_TEXT: 'text',
    INPUT_TEXTAREA: 'textarea',
    INPUT_TOGGLE: 'toggle',
    INPUT_PASSWORD: 'password',
    INPUT_MULTISELECT: 'multiselect',
    INPUT_AUTOCOMPLETE: 'autocomplete',
  },
  COMPONENTS: {
    ALERT: 'alert',
    BADGE: 'badge',
    BUTTON: 'button',
    CARD: 'card',
    SCROLLBAR: 'scrollbar',
    MODAL: 'modal',
    SKELETON: 'skeleton',
    SPINNER: 'spinner',
    TOOLTIP: 'tooltip',
    PROGRESS_BAR: 'progress-bar',
    PROGRESS_SPINNER: 'progress-spinner',
  },
} as const;
