export const TITLE_DEFINITION = {
  APP: {
    HOME: 'Home',
    NOT_FOUND: 'Not Found',
    FOUNDATIONS: 'Foundations',
    FORMS: 'Forms',
    COMPONENTS: 'Components',
    VISUALS: 'Visuals',
  },
  FOUNDATIONS: {
    COLORS: 'Colors',
    TYPOGRAPHY: 'Typography',
  },
  FORMS: {
    INPUT_CHECKBOX: 'Checkbox',
    INPUT_RADIO: 'Radio',
    INPUT_RANGE: 'Range',
    INPUT_SELECT: 'Select',
    INPUT_TEXT: 'Text',
    INPUT_TEXTAREA: 'Textarea',
    INPUT_TOGGLE: 'Toggle',
    INPUT_PASSWORD: 'Password',
    INPUT_MULTISELECT: 'Multiselect',
    INPUT_AUTOCOMPLETE: 'Autocomplete',
    INPUT_NUMBER: 'Number',
  },
  COMPONENTS: {
    ALERT: 'Alert',
    BADGE: 'Badge',
    BUTTON: 'Button',
    CARD: 'Card',
    SCROLLBAR: 'Scrollbar',
    MODAL: 'Modal',
    SKELETON: 'Skeleton',
    SPINNER: 'Spinner',
    TOOLTIP: 'Tooltip',
    PROGRESS_BAR: 'Progress Bar',
    PROGRESS_SPINNER: 'Progress Spinner',
    TOAST: 'Toast',
    NAVIGATION: 'Navigation',
  },
  VISUALS: {
    FLAG: 'Flag',
  },
} as const;
